cleanup-environment-argocd:
  stage: deploy
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-4eyes-argocd'
    branch: 'master'
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true
  #  environment:
  #    name: review/$CI_COMMIT_REF_SLUG
  #    action: stop

cleanup-environment-environment-branch:
  stage: deploy
  needs:
    - cleanup-environment-argocd
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-dev-environment'
    branch: 'development'
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

cleanup-environment-umbrella-chart-branch:
  stage: deploy
  needs:
    - cleanup-environment-environment-branch
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-helm-umbrella-chart-gitlab'
    branch: 'development'
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true
